server:
  port: 85

#默认使用配置
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: @profileActive@
    #active: test
  #topic模式该配置需打开   
  #jms:
   # pub-sub-domain: true
    
#公共配置与profiles选择无关
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath*:/mapper/*/*.xml
  type-aliases-package: com.yuqian.itax
mapper:
  not-empty: false
  identity: MYSQL