spring:
  redis:
    database: 6
    host: r-bp1ghgemm09r4jlrx1.redis.rds.aliyuncs.com
    port: 6379
    password: sd2@jhs722djke1411y3
    jedis:
      pool:
        #可用连接实例的最大数目，默认值为8
        max-active: 512
        #控制一个pool最多有多少个状态为idle(空闲的)的jedis实例，默认值也是8。
        max-idle: 256
        #等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException；
        max-wait: 10000ms
  rabbitmq:
    host: 192.168.0.94
    port: 5672
    username: itax
    password: 123456
    virtual-host: /itax
  #生产配置mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1ai1aw92y2pj341.mysql.rds.aliyuncs.com:3306/itax
    username: itax
    password: DB#ITax@#2020

#设定是否需要进行验签
isCheckSign: true

#Swagger
knife4j:
  # 屏蔽所有Swagger的相关资源
  production: true