spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.100.40:3306/itax_dev #数据同步
    username: itax
    password: itax_7890
  #redis
  redis:
      database: 6
      host: 172.16.100.40
      port: 6379
      password: redis_test123
      jedis:
        pool:
          #可用连接实例的最大数目，默认值为8
          max-active: 512
          #控制一个pool最多有多少个状态为idle(空闲的)的jedis实例，默认值也是8。
          max-idle: 256
          max-wait: 10000ms
  rabbitmq:
    host: 172.16.100.40
    port: 5672
    username: rabbit_itax_dev
    password: 123456
    virtual-host: /itax_dev

#设定是否需要进行验签
isCheckSign : false