server:
  port: 8089
  servlet:
    context-path: /itax-admin
  max-http-header-size: 100000

spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  profiles:
    active: @profileActive@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
      multipart:
        enabled: true
        max-file-size: 100Mb
        max-request-size: 100Mb
  freemarker:
    request-context-attribute: rc

  #公共配置与profiles选择无关
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath*:/mapper/*/*.xml
  type-aliases-package: com.yuqian.itax
mapper:
  not-empty: false
  identity: MYSQL
knife4j:
  # 屏蔽所有Swagger的相关资源
  production: true
  basic:
    # 开启Swagger的Basic认证功能,默认是false
    enable: true
    # Basic认证用户名
    username: itax
    # Basic认证密码
    password: 123456
